export const COUNTRIES = [
 { shortName: "ae", fullName: "United Arab Emirates" },
 { shortName: "ar", fullName: "Argentina" },
 { shortName: "at", fullName: "Austria" },
 { shortName: "au", fullName: "Australia" },
 { shortName: "be", fullName: "Belgium" },
 { shortName: "bg", fullName: "Bulgaria" },
 { shortName: "br", fullName: "Brazil" },
 { shortName: "ca", fullName: "Canada" },
 { shortName: "ch", fullName: "Switzerland" },
 { shortName: "cn", fullName: "China" },
 { shortName: "co", fullName: "Colombia" },
 { shortName: "cu", fullName: "Cuba" },
 { shortName: "cz", fullName: "Czech Republic" },
 { shortName: "de", fullName: "Germany" },
 { shortName: "eg", fullName: "Egypt" },
 { shortName: "fr", fullName: "France" },
 { shortName: "gb", fullName: "United Kingdom" },
 { shortName: "gr", fullName: "Greece" },
 { shortName: "hk", fullName: "Hong Kong" },
 { shortName: "hu", fullName: "Hungary" },
 { shortName: "id", fullName: "Indonesia" },
 { shortName: "ie", fullName: "Ireland" },
 { shortName: "il", fullName: "Israel" },
 { shortName: "in", fullName: "India" },
 { shortName: "it", fullName: "Italy" },
 { shortName: "jp", fullName: "Japan" },
 { shortName: "kr", fullName: "South Korea" },
 { shortName: "lt", fullName: "Lithuania" },
 { shortName: "lv", fullName: "Latvia" },
 { shortName: "ma", fullName: "Morocco" },
 { shortName: "mx", fullName: "Mexico" },
 { shortName: "my", fullName: "Malaysia" },
 { shortName: "ng", fullName: "Nigeria" },
 { shortName: "nl", fullName: "Netherlands" },
 { shortName: "no", fullName: "Norway" },
 { shortName: "nz", fullName: "New Zealand" },
 { shortName: "ph", fullName: "Philippines" },
 { shortName: "pl", fullName: "Poland" },
 { shortName: "pt", fullName: "Portugal" },
 { shortName: "ro", fullName: "Romania" },
 { shortName: "rs", fullName: "Serbia" },
 { shortName: "ru", fullName: "Russia" },
 { shortName: "sa", fullName: "Saudi Arabia" },
 { shortName: "se", fullName: "Sweden" },
 { shortName: "sg", fullName: "Singapore" },
 { shortName: "si", fullName: "Slovenia" },
 { shortName: "sk", fullName: "Slovakia" },
 { shortName: "th", fullName: "Thailand" },
 { shortName: "tr", fullName: "Turkey" },
 { shortName: "tw", fullName: "Taiwan" },
 { shortName: "ua", fullName: "Ukraine" },
 { shortName: "us", fullName: "United States" },
 { shortName: "ve", fullName: "Venezuela" },
 { shortName: "za", fullName: "South Africa" }
];